### ISSUE TITLE
Bug and Feature Requests

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#1]
### **Bug**
Stuttering always happens when scrolling to the next page.

1. The stuttering always happens when going to the next page no matter the page settings.

### **Feature**
I noticed that the application resizes large images to the width automatically to fit them to the display.

1. It would be better to provide an option to show images in 'original size' and 'fit to width' separately.
2. Read with manga reader option in the 'file explorer context menu'.
3. Customizable shortcuts at least for previous chapter / next chapter.
4. A portable version.
5. When opening the app show app logo instead of a colorful rectangular box.

**Comment by mienaiyami** [comment]
Thanks for your feedback.

### Bug
1.  I will try to fix this bug as soon as possible

### Features

1. I believe i do have this feature.  ![image width](https://user-images.githubusercontent.com/84740082/196026217-df879d76-4928-4d07-869e-b4de7f9242e3.png) But it only extend to 100% of screen width to prevent horizontal scrolling, but if you want it to extend over 100% of screen where you can scroll horizontally, please make a new issue.
2. Thanks for suggestion. I will add a option in settings to enable/disable that.
3. Will be adding in next update.
4. If you a .zip of whole app, I will be providing that in next update. But if you want a smaller one standalone .exe version, that isnt possible with the the framework im using. I am working on this, but it will take some time as I would need to rewrite most of the code.
5. I didnt know it shows a colorful rectangular box when opening the app as it opens instantly for me(make sure you are launching app from start menu or desktop shortcut and not the Installer you downloaded from github). Also i dont hv any app icon, im using default generated when i compile the app 

**Also sorry, you will have to install next update manually. But from then on it will install automatically.**
If you have any more issues or requests, please don't be hesitant to make "New Issue"

**Comment by mienaiyami** [comment]
If you want, you can give me keys for previous chapter / next chapter shortcut so i can add them in today's update. Making shortcuts customizable will take some time, and will be uploaded by a week from today . Thats the least i can do for the only user of this app beside me
