### ISSUE TITLE
Bug In Theme Maker

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#13]
### 1. Bug '--topBar-color'

- I changed the body of the manga reader to black using '--body-bg' property, but the side list color remained the same.
- The side list is linked to '--topBar-color', instead of '--body-bg' property.
- Because of it, if I try to change the side list color, top bar color also changes with it.

**Comment by mienaiyami** [comment]
Sorry, I was being lazy while doing that. Will fix this soon. Also, you might want to copy paste "shortcuts.json" from appdata("%appdata%/Manga Reader/") folder because an update bug will delete it.

**Comment by mienaiyami** [comment]
You should be able to find "--sideList-bg" in next update. Open issue again if have any queries.
