### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#14]
### 1. Option to hide/show the page counter in full screen/zen mode.
- Place the page counter at the bottom right end of the screen, only in the zen mode, if possible.

### 2. Reset Button beside the color/Opacity to reset to the default value.
![image](https://user-images.githubusercontent.com/111482404/200273107-8fbb65fa-f95d-4de6-a0f3-793ca0554739.png)

**Comment by mienaiyami** [comment]
Yeah, sure. It is here because old version of app didn't have page indicator. This app is very rough as I'm solo and newbie developer and this is my first project.
