### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#2]
Thanks for the responding to my previous suggestions. Some new feature requests.

1. A full screen mode option.
- To make the reading more immersive only images are to be shown and no side menus, no scroll bars, no left pin in full screen mode.
2. An option to check or uncheck auto updates.
3. In reader settings, under other settings, make the font larger.
4. A pure dark/black theme option. theme1 seems like gray, theme2 dark blue, theme3 white.
5. What I meant by portable is that the app must save the user data, bookmarks in the portable folder only.
- Example [Hakuneko Portable v6.1.7 Manga Downloader](https://github.com/manga-download/hakuneko/releases/tag/v6.1.7).

**Comment by mienaiyami** [comment]
Thanks for suggestions, all of these will be in today's update, except "pure dark theme" which will be added soon
