### ISSUE TITLE
Zoom Size

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#3]
- I am confused about the zoom size system you use in the manga reader.
- The zoom size is depended on the screen size rather than the manga image.
- For example when I open a manga chapter (all images containing 1000x1600), the zoom size shows < 100%, until the image is fit to the screen completely, only then it shows 100%.

**Comment by mienaiyami** [comment]
Sorry but I'm not quite sure how you want it, but there's a reason for current zooming system. 

- If zoom is set to 60%, images will cover 60% of screen unless width of image is equal or higher that its height (and **"variable image size"** is checked in "reader settings > other settings"), **then it will cover 60% x 2 = 120%** but I limit it to 100% of screen width so you don't have to scroll horizontally. This system is usually for manga where most pages are individual, but some can be of two-page span (big panels), so with this system two-page span images can have same text size as one-page images. 
- If you mean you want to zoom more than 100%, I will increase limit to 300% in next update.

Also, I think I might have miss interpreted when you said, "stuttering when scrolling". I noticed it cause stuttering once when images are of big size. I will try my best to fix it.
