### ISSUE TITLE
jpeg는 인식 안되나요?

### ISSUE THREAD

**Issue by jjung3831** [mienaiyami/react-ts-offline-manga-reader#38]
### Question

thank you zip recognition.

Is it possible to support jpeg?

Webtoon extension jpeg.

**Comment by mienaiyami** [comment]
jpeg is supported since first version. You might be not opening folder in right way, click on arrow icon beside folder name (in first tab) which contains jpeg or any other image format or click on folder then click on "open" button below search bar.
If problem is solved, close issue or just reply.

**Comment by jjung3831** [comment]
jpg open
no jepg
file link
![01](https://user-images.githubusercontent.com/113493187/209766979-44ef28c9-ed0d-424b-873e-0c889829c63b.png)



[32231321213.zip](https://github.com/mienaiyami/react-ts-offline-manga-reader/files/10312474/32231321213.zip)

**Comment by mienaiyami** [comment]
Thanks for screenshot. It seems problem is the extension name, this app does supports jpeg but since your extension is JPEG (in capital), it is not able to detect the image. I will fix this issue in next update (possibly today).

**Comment by mienaiyami** [comment]
Sorry, but you will need to manually update to next version. Previous one had some downloading errors.
