### ISSUE TITLE
UI scale

### ISSUE THREAD

**Issue by omodia** [mienaiyami/react-ts-offline-manga-reader#45]
### Steps to reproduce

1. Increase UI scale using Ctrl +/= (Do this 2-3 times, it depends on display, but 2-3 times should do it)
2. Open any manga
3. Open Reader settings

### ✔️ Expected Behavior

Everything works fine and the size increases for fonts, objects and all.

### ❌ Actual Behavior

Reader settings size also increases, but the bottom settings disappear.
What I mean is that they are not possible to scroll down to.

**Comment by mienaiyami** [comment]
Fixed, will be released soon.
