### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#5]
### Suggestion to make this manga reader more searchable on github.

- I have searched github many times for a manga and webtoon reader and I could not find this manga reader, until I viewed almost all the available manga readers on github.

### Tags

The tags you currently use are windows, typescript, reactjs, desktop, electronjs. Adding other relevant tags would be better, like,
- manga reader
- manga viewer
- manga
- comic
- manhwa
- manhua
- webtoon
- comic reader
- comic viewer
- manhwa reader
- manhwa viewer
- manhua reader
- manhua viewer
- webtoon reader
- webtoon viewer
- infinite scrolling
- continuous scrolling
- vertical scrolling
- image viewer
- continuous image viewer
- vertical image viewer
- cbz reader
- cbz viewer
- cbr reader
- cbr viewer, etc.

I have used many popular manga readers like, html mangareader, CDisplay Ex, OpenComic, YAC Reader and many others, and I found this to be the best manga/webtoon reader. 

Minimal CS Manga Reader is the next best only for its UI, but it takes up too much memory and cannot even open large images and is dependent on .net. But its UI is one of the best among the manga readers that I have used.

**Comment by mienaiyami** [comment]
Thank you very much for choosing my manga reader. I initially just made it for myself and wasn't expecting anyone to use it so it doesn't even have a name yet. I will try to improve UI and performance further
