### ISSUE TITLE
Chapter Information Screen in v2.5.0

### ISSUE THREAD

**Issue by omodia** [mienaiyami/react-ts-offline-manga-reader#51]
### Issue

> Added screen to show previous/current/next chapter when in start/end of chapter for `zen mode`.

- The screen also appears outside of zen mode.
- Please provide an option in reader settings to enable/disable the screen completely.

**Comment by mienaiyami** [comment]
> Please provide an option in reader settings to enable/disable the screen completely.

Should this setting apply to zen mode as well. And I will be adding it in main settings as it will clutter reader settings.

**Comment by mienaiyami** [comment]
This feature was mainly added for `click to move` reader mode because without a stopping screen holding moving keys will indefinitely open prev/next chapters.
