### ISSUE TITLE
UI Suggestion/Request

### ISSUE THREAD

**Issue by omodia** [mienaiyami/react-ts-offline-manga-reader#60]
### - The highlighted buttons look good, but more space between the sentences.

![4](https://user-images.githubusercontent.com/116664905/218645190-f0547089-6ce7-4d5b-9e37-5e09495ea135.png)

### 2. Max Width
- Renaming it to 'Images max width' would be more relevant and a button beside it.
![image](https://user-images.githubusercontent.com/116664905/218645574-bb7e788b-8a44-4a06-b005-74bfd359f018.png)

### 3. Large Spaces
- The UI feels a bit cluttered mainly because of the large spaces beside the values.
- Keep the 'px' as it is, but please remove the large space at values place. It is unnecessary.

### 4. Suggested UI
![1](https://user-images.githubusercontent.com/116664905/218525378-ce8bb8cf-15a7-4e07-aff5-7cd1c4b41f0e.png)

### - Brackets are unnecessary.

![2](https://user-images.githubusercontent.com/116664905/218526603-58df2921-0b35-4c8b-b10e-bcdb49598617.png)

### - Numbering would be better for the main sentence and bulletin for the sub sentence.

![3](https://user-images.githubusercontent.com/116664905/218528368-04531507-65af-4314-bc0a-fdde48345c24.png)

**Comment by mienaiyami** [comment]
Thanks for visuals. I'll try my best to make it look better.

**Comment by mienaiyami** [comment]
> Titles and Space between Reset, Link buttons and color-opacity.

After asking some more user, I have decided to keep it as the way it is.

> Numbering for the main sentence and bulletins for the sub sentence.

Numbered list are only supposed to be used when there is a sequence or order. 

> In between each main sentence a line separating them. I could not properly draw the lines here.

I tried it but it make UI look more cluttered. And besides they are unimportant unlike in shortcuts/theme maker.


I will be implementing rest.
