### ISSUE TITLE
Limit Gap between Pages max value px

### ISSUE THREAD

**Issue by omodia** [mienaiyami/react-ts-offline-manga-reader#61]
### - Generally 10 px - 20 px is used for reading manga, if page gap is needed.

**Comment by mienaiyami** [comment]
I did think about it when I was adding this feature, and the conclusion was to keep it a higher limit. I couldn't think of any case where that high limit could affect UX but there were cases where not having a higher limit will affect UX.
If you are able to provide a good reason, i might limit it.
