### ISSUE TITLE
New and previously known Bugs

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#7]
Thanks for your hard work for making customizable shortcuts and full screen mode available.

I have checked out the latest update and found some new bugs.
### Bugs

Only when the side list is pinned,

1. Scrolling is no longer possible using mouse cursor.
2. The page number display counting does not work. The number freezes at 1.
3. Even clicking on the center of image (little bit to the left or right) makes the chapter change. This happens even when the side list is unpinned.
4.  When full screen/zen mode is activated, the images become very small and are pinned to the left side of the screen.

**Comment by mienaiyami** [comment]
Thank you for reporting issues. It's very hard for me to test everything alone.

**Comment by mienaiyami** [comment]
Also let me know if there's still stuttering because I can't see any when scrolling 2k images.

**Comment by mienaiyami** [comment]
> What does clamp mean in the reader settings under zoom size? ![image](https://user-images.githubusercontent.com/111482404/198559498-e1f06b59-c97a-47e9-9645-2e37dbc9e919.png)

When unchecked you can zoom up to 500% (but it will stop on a limit set by framework according to resolution of image).
I added clamp option to limit it to 100% so if you use ctrl+scroll to change size so it doesn't create mess
