### ISSUE TITLE
Memory And Cpu Usage

### ISSUE THREAD

**Issue by alenwai** [mienaiyami/react-ts-offline-manga-reader#8]
- ### CPU Usage When stutter keeps on happening while scrolling down images.

https://user-images.githubusercontent.com/111482404/198818944-c49b7445-6f4b-4727-9bb0-89aa8c53e3ef.mp4

### I have also noticed the memory usage not going down even after being idle for 10 minutes.
- After cycling through folders and going back to the starting folder, shouldn't it have the same memory usage when started. Here it is using more memory after cycling through 4 folders and going back to folder-1.
- Some Examples below.

### Example 1 - Folder Size= 4.86 MB, Total Images = 17, Resolution = 1760 x varies (height x width).
- After cycling through 4 folders and going back to folder 1, the usage is shown below.
1.  **Red =** Images loaded and cycled through 4 folders and after going back to folder-1.
2.  **Green =** Same folder-1 loaded as red, but when it did not cycle through any folder. Remained constant at folder-1.

![1 - Below 3 minutes of Being Idle, no usage](https://user-images.githubusercontent.com/111482404/198817837-ff922456-c43e-4df3-94be-242565d88686.jpg)

![2 - After 3 to 5 Minutes of Being Idle, no usage](https://user-images.githubusercontent.com/111482404/198817844-42a0f33a-3842-4ee7-967e-06b8c0a2aed7.jpg)

### Example 2 - Folder Size= 27.5 MB, Total Images = 58, Resolution = 2400 x varies (height x width).

- After cycling through 4 folders and going back to folder 1, the usage is shown below.
1.  **Red =** Images loaded and cycled through 4 folders and after going back to folder-1.
2.  **Green =** Same folder-1 loaded as red, but when it did not cycle through any folder. Remained constant at folder-1.
3. **White =** Manga Reader Home Screen. No Images Loaded.

- ### After 9 Minutes of Being Idle, no usage. The memory usage did not go down.

![After 9 Minutes of Being Idle, no usage](https://user-images.githubusercontent.com/111482404/198818164-4c38b9c1-69f4-4aac-9e0f-0d313251ee38.jpg)

**Comment by mienaiyami** [comment]
I was already looking into it for quite a while. But i have found no results, it all depends on electron framework I'm using and unfortunately there's not many options in it. Take discord for example, its build in same framework and it has a lot higher ram usage. It is because of the way this framework load images, if you scroll down to bottom of a folder then open another (without refreshing) and go back to first, you will notice that there no stutter on first folder.

Regardless, I'll keep looking for a solution and try to improve it.

**Comment by mienaiyami** [comment]
> * I tried adding custom theme, but I could not make it work. I prefer a pure dark theme when reading manga. Can you add it, if it is possible.

Don't worry about it, I'm already working on theme maker inside settings just like shortcuts.
